### PR TITLE
svdtools 0.2.6

### PR DESCRIPTION
**Pull request by burrbull**
For https://github.com/stm32-rs/svdtools/pull/89

### CODE REVIEW

**Comment by adamgreig** [comment]
svdtools 0.2.6 is released now, should be able to update this PR to use it

**Comment by burrbull** [comment]
> 

1 minute

**Comment by burrbull** [comment]
Done

**Review by adamgreig — APPROVED** [review]
Thanks, looks good!

I've checked manually since the mmap action won't work until after this is merged. Unfortunately the mmap generation currently doesn't take into account derived registers (https://github.com/stm32-rs/svdtools/issues/122) so it thinks the TSTR etc regs have lost all their fields, but the actual svd files (and the svd2rust generation) do the right thing.

Besides that there's no change caused by this PR, so LGTM.

bors r+

**Pull request merged**
