### PR TITLE
More clusters

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
This is all for now.

**Comment by burrbull** [comment]
Conflicts are resolved.

**Comment by adamgreig** [comment]
Thanks for the update. The new clusters look good and I'm happy to merge them, but please could you move the changes to the SVDs (`_add` and `_delete` and `_modify`) into files in `devices/common_patches/` rather than inside `peripherals/`?

The objective is to keep the SVD modifications in `devices/` so they can be correctly applied per device that requires them, and then the SVD annotations (adding enumerations/ranges) in `peripherals/`.

**Comment by burrbull** [comment]
Done.

It’s great that you separated patches and annotations.
But it would be even better if there was an opportunity to get the patched SVDs without annotations.
I mean split `make patch` in two steps without and with annotations.
It would help me to find more typos in svds.

**Comment by burrbull** [comment]
Yes, patch-only would be great.

**Comment by burrbull** [comment]
bors try

**Comment by burrbull** [comment]
Hi, @adamgreig . How about merge or review? 2 months have passed.

**Comment by adamgreig** [comment]
Sorry for the delay! I haven't had much time to review PRs the last few weeks. I'll try to get these and other pending PRs released soon.

**Pull request merged**
