### PR TITLE
field arrays

### PR DESCRIPTION
**Pull request by burrbull**
See https://github.com/rust-embedded/svd2rust/pull/400

### CODE REVIEW

**Comment by adamgreig** [comment]
We should probably delete that mmap script; the makefile uses `svd mmap` from svdtools.

**Comment by burrbull** [comment]
Requires https://github.com/stm32-rs/svdtools/pull/66

**Comment by burrbull** [comment]
cc @adamgreig Oldest PR finally passes CI.

**Comment by burrbull** [comment]
cc @newAM review, please

**Comment by newAM** [comment]
FYI this has merge conflicts now after the OTG PR.

**Comment by burrbull** [comment]
replaced with #924

**Pull request closed without merging**
