### PR TITLE
check `CARGO_HOME` env var

### PR DESCRIPTION
**Pull request by eZioPan**
check `CARGO_HOME` env var before put binary into default place

### CODE REVIEW

**Comment by eZioPan** [comment]
Are my changes conflict with CI workflow? The script runs fine on my linux machine.

**Comment by adamgreig** [comment]
The CI failure is in the alternative cargo-make based `Makefile.toml` rather than the regular `Makefile`. I guess it's somehow ending up installing the tools to a directory that's not on PATH or something like that... if you run `cargo make` locally does it work out?

**Comment by eZioPan** [comment]
`cargo make` run smoothly on my local linux machine. The only en vars I add is `RUSTUP_HOME` and `CARGO_HOME`.

**Comment by eZioPan** [comment]
it's weird, in CI, PATH env inlude `${CARGO_HOME}/bin/` https://github.com/stm32-rs/stm32-rs/actions/runs/5239385480/jobs/9459159924

**Comment by eZioPan** [comment]
@adamgreig sorry for take that long time to fix the bug. I would ask a review on this again.

**Pull request closed without merging**
