### PR TITLE
G471 Add OPAMP6

### PR DESCRIPTION
**Pull request by usbalbin**
Hopefully the last PR for now :)

### CODE REVIEW

**Comment by burrbull** [comment]
Is this normal that there is OPAMP6, but there are not OPAMP4/5?

**Comment by usbalbin** [comment]
I will gether some more info just to be safe.

**Comment by usbalbin** [comment]
There seems to be something weird here. I can not even find STM32G471 on ST's website except for errata and RM. I have also searched mouser, digikey.

I also find it on [ARM's website](https://www.keil.arm.com/devices/stmicroelectronics-stm32g471ceux/features/) but that is pretty much it.

What do we want to do here?

**Comment by burrbull** [comment]
> What do we want to do here?

I can merge this PR unchanged.
But if there are all 6 registers are available I'd merge them in register array.

**Comment by usbalbin** [comment]
What little info I can find says it only has OPAMP1, OPAMP2, OPAMP3 and OPAMP6. Thus a total of 4 op amps. This is also the same as for G491 and G4A1(however they can be found) they have the same set of op amps.

**Review by burrbull — APPROVED** [review]

**Comment by usbalbin** [comment]
Thanks :)

**Pull request merged**
