### PR TITLE
Apply USB OTG FS fixes on STM32F446

### PR DESCRIPTION
**Pull request by FLamparski**
Attempts to address some of #327 for STM32F446 by applying existing USB OTG patches. These result in a more correct SVD file being used, fixing the `DIEPTXF0`/`GNPTXFSIZ` misnomer and adding `GRXSTSP`.

### CODE REVIEW

**Comment by Disasm** [comment]
STM32F446 requires another set of fixes. `otg_{fs|hs}_fixes.yaml` applies to F429 and similar chips with Core ID `0x0000_1200/0x0000_1100`. F446 chip has Core ID `0x0000_2000/0x0000_2100` and slightly different registers/fields.

**Comment by thousandeyes-fwieland** [comment]
That might be the case but I've looked through the reference manual and the modifications from the fixes files do match the layout given there. Maybe the way forward would be to split up the `otg_{hs|fs}_fixes.yaml` by the range of parts they best apply to? Given that already there seem to be 3 different versions of that peripheral in the f4 range alone in this library.

**Comment by Disasm** [comment]
I think it's better to make something like `otg_{hs|fs}_v2_fixes.yaml`, complete them, and then start thinking about moving common fixes into a separate file.

**Comment by FLamparski** [comment]
Hmm, having had a look at the general breakdown of USB features in [AN4879](https://www.st.com/content/ccc/resource/technical/document/application_note/group0/0b/10/63/76/87/7a/47/4b/DM00296349/files/DM00296349.pdf/jcr:content/translations/en.DM00296349.pdf) I'd probably go with creating a fixes file for each column in Table 5, which is what I'm going to do for the F446 part in this PR

**Comment by FLamparski** [comment]
image

I should probably fix the descriptions but basically the register-level `_derive` is working and some of the missing registers can be added back - the SVD is missing endpoints 4 and 5 in basically all endpoint registers in the FS peripheral, and it looks like some of the registers are given on the wrong address compared to the datasheet. I'll probably poke some more on this still.

**Comment by FLamparski** [comment]
It looks like most of the memory map in the SVD is wrong for the 446, if the datasheet is taken as the truth 😢

**Comment by Disasm** [comment]
Yes, if you compare original F429 and F446 SVDs, you can see they have almost identical USB peripherals, but this is not true. Reference Manual is more reliable source of information.

**Comment by FLamparski** [comment]
Oh never mind - I didn't realise that the address offsets given in the SVD are relative to OTG_FS_DEVICE rather than OTG_FS as a whole, as is given in the datasheet. Grrr!

**Comment by FLamparski** [comment]
@Disasm this should be it - I've added registers for the missing endpoints and it looks like the addresses do match the reference manual now. I don't think I'll be able to check whether this works with the synopsys-otg driver for a while though

**Comment by adamgreig** [comment]
I've merged this manually to resolve the build conflicts, thanks for the PR! I appreciate there are some TODOs left; it seemed useful to get what you've got so far merged but please feel free to add more later.

**Pull request merged**
