### PR TITLE
[WIP] STM32G0 updates

### PR DESCRIPTION
**Pull request by dotcypress**
Fine grain features for stm32g0 family

### CODE REVIEW

**Comment by adamgreig** [comment]
Hmm, sorry, I missed the WIP flag this go around. Do you want these merged?

bors r-

**Comment by dotcypress** [comment]
@adamgreig I want to port `stm32g0-hal` before, sorry for incomplete PR.

**Comment by adamgreig** [comment]
No problem, just let me know when it's ready.

**Comment by dotcypress** [comment]
@adamgreig ready for merge, thank you ;)

**Pull request merged**
