### PR TITLE
shorter registernames for stm32l4 devices of the COMP registers + add…

### PR DESCRIPTION
**Pull request by oldsheep68**
…ing the register descriptions

Changes in: crates stm32l4x1, crates stm32l4x2, crates stm32l4x3, crates stm32l4x5, crates stm32l4x6

registers of the comparator have been renamed, example: from comp1_en -> en
this makes a more generic use in programming possible

Furthermore, the description has been added for all comp  

During this work, I found the following topics, where I do not know, how to address:

1)
Reference Manual RM0394: is valid for: STM32L443 and STM32L433; but I had to add the register description in the device descriptors stm32l4x3 of RM0351

2) 
The device STM32L471 is part of stm32l4x1, but is in RM0351 whereas all other devices are part of RM0394

### CODE REVIEW

**Comment by burrbull** [comment]
You can simplify this using `_strip`:

```yaml
COMP:
  COMP1_CSR:
    _strip:
      - "COMP1_"
  COMP2_CSR:
    _strip:
      - "COMP2_"
```

**Comment by oldsheep68** [comment]
Hi burbull
Thanks great solution. I am going to test the simplified version you recommend, and will check in the modified variant of register modification.

**Review by adamgreig — APPROVED** [review]
Thanks, looks good! I noticed one typo (256 instead of 255) that I fixed.

bors r+

**Review by adamgreig — APPROVED** [review]
Rebased to fix merge conflicts.

bors r+

**Review by adamgreig — APPROVED** [review]
bors r+

**Pull request merged**
