### PR TITLE
update G4 source

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
cc @usbalbin

**Comment by usbalbin** [comment]
I will try to take a look at this later

**Comment by usbalbin** [comment]
I am not quite sure how to review something like this. The mem map diff is quite a lot

**Comment by usbalbin** [comment]
One thing I have noticed is that the PWR registers like [`cr1`](https://stm32-rs.github.io/stm32-rs/STM32G484xx.html#PWR:CR1) etc now have `pwr_` as prefix which they did not before

**Comment by usbalbin** [comment]
[Here](https://github.com/stm32-rs/stm32g4xx-hal/compare/staged-pac...usbalbin:stm32g4xx-hal:update_for_new_pac?expand=1) are the changes to get the hal to compile

**Comment by burrbull** [comment]
> now have `pwr_` as prefix which they did not before.

fixed

**Comment by burrbull** [comment]
Please reopen it when you finish to review.

**Comment by usbalbin** [comment]
> Please reopen it when you finish to review.

Sure, however I can not speak as to if anything else has changed like addresses or bit positions being changed by accident. Do you know if there is any way of checking that which does not involve manually checking tens of thousand lines of code? :)

**Comment by burrbull** [comment]
you can use "cargo make yamls" to generate

**Comment by usbalbin** [comment]
> you can use "cargo make yamls" to generate

Doing this for the base branch and this PR and comparing the yamls still generates very large diffs. A big part of that diff is just different sorting of the yaml which I found hard to review. Do you know any way to make that easier? Is it possible to sort yaml without affecting the data?

**Comment by burrbull** [comment]
You can try to add `--format_config PATH` to `convert` https://github.com/stm32-rs/stm32-rs/blob/794b963b832ba4299300786ef3fc8120487c68ef/Makefile.toml#L247
with `sorting` entries:
https://docs.rs/svd-encoder/latest/svd_encoder/struct.Config.html#structfield.field_sorting

**Comment by usbalbin** [comment]
> You can try to add `--format_config PATH` to `convert`
> 
> https://github.com/stm32-rs/stm32-rs/blob/794b963b832ba4299300786ef3fc8120487c68ef/Makefile.toml#L247
> 
> 
> with `sorting` entries:
> https://docs.rs/svd-encoder/latest/svd_encoder/struct.Config.html#structfield.field_sorting

Thanks, I will try :)

**Comment by usbalbin** [comment]
I changed Makefile.toml

```diff
-          exec ${command} convert --input-format xml ${patchedpath} ${ymlpath} 
+          exec ${command} convert --input-format xml ${patchedpath} ${ymlpath} --format-config cfg_sorted.json
```

with these different cfg_sorted.json, the order of the fields does not seem to change. `yaml/stm32g484.yaml` stays the same.

```json
{}
```

```json
{
    "field_sorting": "Unchanged,Offset"
}
```

```json
{
    "field_sorting": "Unchanged,OffsetReserved"
}
```

```json
{
    "field_sorting": "DeriveLast,Offset"
}
```

Am I doing something wrong?

**Pull request closed without merging**
