### PR TITLE
Fixed various issues with L4 and WB take 2

### LINKED ISSUE #555: L41x and L42x use diff RTC regs
L4 PAC RTC doesn't work on 41x and 42x. Distinction is on 3rd digit. RM has sep RTC sections. PAC only uses 43+ one. CR is on a diff address, so this is fundamentally incompatible.

I'm not sure how to address this: The PAC split on 3rd digit works for most other periphs. Probably add 2 sep RTC modules, like how the RM has 2 sep chapters.

My best thought on an approach: Use two separate RTC modules, in the vein of how the RM splits it up into 2 chapters.

### PR DESCRIPTION
**Pull request by David-OConnor**
Fixes #555, #563, #565, #567, #570, #572, and #575.

See https://github.com/stm32-rs/stm32-rs/pull/573; "unrecoverable" git errors.

### CODE REVIEW

**Comment by David-OConnor** [comment]
The 412 RTC changes don't appear to be taking effect, after building and inspecting the module. Any ideas?

**Comment by adamgreig** [comment]
I guess the problem is with the `_include: stm32l4x2.yaml` at the end; I suspect that will overwrite things you don't want to overwrite, such as `_svd`, in the parent YAML. I don't think it's intended that you'd import a top-level YAML into another top-level YAML, so that's my guess as to the problem. Try just including the relevant bits of that file directly?

By the way, instead of changing the SVD zip file (which should ideally be exactly as-downloaded from ST), you can modify `extract.sh` to add a new copy line to create a new identical SVD for L412, like https://github.com/stm32-rs/stm32-rs/blob/master/svd/extract.sh#L9

**Comment by David-OConnor** [comment]
Done! That sorted it. Marking as draft for now; running into empty built-libs on L4x3, L412, and WB55, for reasons I haven't yet determined.

**Comment by David-OConnor** [comment]
Fixed the not-building problems; various syntax errors, eg `read` instead of `read-only`. Currently, some of the L412 RTC reg changes are taking place, but not others, upon generated-module inspection. I wonder if this is an order-error, eg if a reg is added to a place that's not yet freed from a later-modified reg. (?)

**Comment by David-OConnor** [comment]
Fixed most L412 RTC problems; syntax error re ordering of `_modify` and the reg name. Currently looks good, except 3 out of 4 of the added regs (at the end of the block) are not adding. Maybe need to increase size of reg block somehow?

**Comment by David-OConnor** [comment]
Broke git again

#576

**Pull request closed without merging**
