### PR TITLE
svdpatch classes

### PR DESCRIPTION
**Pull request by burrbull**
Entirely aesthetic patch.

### CODE REVIEW

**Comment by adamgreig** [comment]
On the whole I like this PR, thanks! The script probably should have used classes from the beginning. I'll need a little more time to review it as I'm quite busy the next couple of days and want to check it carefully.

**Comment by adamgreig** [comment]
I'm happy with the changes but please fix the merge conflict and then I'll merge this in.

**Comment by burrbull** [comment]
Done.

I sleep when you merge :).

**Pull request merged**
