### PR TITLE
Added missing Enumerations.

### PR DESCRIPTION
**Pull request by taylorh140**
Somehow the remaining EXTSEL bits seem to have been lost. I added them.

### CODE REVIEW

**Comment by taylorh140** [comment]
So just to aid in the review:
[EXTSEL](https://www.st.com/resource/en/reference_manual/dm00031020-stm32f405-415-stm32f407-417-stm32f427-437-and-stm32f429-439-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=418)
should pull up page 418.

**Comment by burrbull** [comment]
Have you checked all reference manuals related to `adc_v2.yaml`?
Looks like not all chips support all of these values

**Comment by taylorh140** [comment]
@burrbull It took me quite a while just to check that the stm32f429 was linked to that YAML file. How does the linking work with these? Also, it is a direct superset of the existing file, so would be better for it to be available?

**Comment by burrbull** [comment]
When you run `make patch` in `.deps` directory script creates `.d` file for each chip with all related yamls.
Possibly it could help you.

**Comment by taylorh140** [comment]
So I think it's really possible I got this wrong. I now see that the yaml has an inheritance.
adc_v2 <-  adc_v2_single <- adc_v2_multi

| adc_v2    | adc_v2_single | adc_v2_multi |
|-----------|---------------|--------------|
| stm32f401 | stm32f410     | stm32f215    |
| stm32f411 | stm32f412     | stm32f217    |
|           | stm32f413     | stm32f405    |
|           |               | stm32f407    |
|           |               | stm32f427    |
|           |               | **stm32f429**    |
|           |               | stm32f446    |
|           |               | stm32f469    |
|           |               | stm32f730    |
|           |               | stm32f745    |
|           |               | stm32f750    |
|           |               | stm32f765    |
|           |               | stm32f7x2    |
|           |               | stm32f7x3    |
|           |               | stm32f7x6    |
|           |               | stm32f7x7    |
|           |               | stm32f7x9    |

## adc_v2

[STM32f411](https://www.st.com/resource/en/reference_manual/rm0383-stm32f411xce-advanced-armbased-32bit-mcus-stmicroelectronics.pdf#page=231) 
[STM32f401](https://www.st.com/resource/en/reference_manual/dm00096844-stm32f401xb-c-and-stm32f401xd-e-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=232)

0000: Timer 1 CC1 event
0001: Timer 1 CC2 event
0010: Timer 1 CC3 event
0011: Timer 2 CC2 event
0100: Timer 2 CC3 event
0101: Timer 2 CC4 event
0110: Timer 2 TRGO event
0111: Timer 3 CC1 event
1000: Timer 3 TRGO event
1001: Timer 4 CC4 event
1010: Timer 5 CC1 event
1011: Timer 5 CC2 event
1100: Timer 5 CC3 event
1101: Reserved 
1110: Reserved
1111: EXTI line11

## adc_v2_single 

[STM32410 << DIFFERENT THAN OTHER adc_v2_single ](https://www.st.com/resource/en/reference_manual/dm00180366-stm32f410-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=232)

0000: Timer 1 CC1 event
0001: Timer 1 CC2 event
0010: Timer 1 CC3 event
1010: Timer 5 CC1 event
1011: Timer 5 CC2 event
1100: Timer 5 CC3 event
1111: EXTI line 11

[STM32F412](https://www.st.com/resource/en/reference_manual/dm00180369-stm32f412-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=336)
[STM32F413](https://www.st.com/resource/en/reference_manual/rm0430-stm32f413423-advanced-armbased-32bit-mcus-stmicroelectronics.pdf#page=354)

0000: Timer 1 CC1 event
0001: Timer 1 CC2 event
0010: Timer 1 CC3 event
0011: Timer 2 CC2 event
0100: Timer 2 CC3 event
0101: Timer 2 CC4 event
0110: Timer 2 TRGO event
0111: Timer 3 CC1 event
1000: Timer 3 TRGO event
1001: Timer 4 CC4 event
1010: Timer 5 CC1 event
1011: Timer 5 CC2 event
1100: Timer 5 CC3 event
1101: Timer 8 CC1 event
1110: Timer 8 TRGO event
1111: EXTI line 11

## adc_v2_multi 

[STM32F205 STM32F207](https://www.st.com/resource/en/reference_manual/cd00225773-stm32f205xx-stm32f207xx-stm32f215xx-and-stm32f217xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=242)
[STM32F405 STM32F407 STM32F427 STM32F429](https://www.st.com/resource/en/reference_manual/dm00031020-stm32f405-415-stm32f407-417-stm32f427-437-and-stm32f429-439-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=418)
[STM32F446](https://www.st.com/resource/en/reference_manual/rm0390-stm32f446xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf#page=387)
[STM32F469 Spec Missing from normal location](https://www.st.com/resource/en/reference_manual/dm00127514-stm32f469xx-and-stm32f479xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=438)
[STM32F469 alternate page](https://www.st.com/resource/en/reference_manual/dm00127514-stm32f469xx-and-stm32f479xx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=419)

0000: Timer 1 CC1 event
0001: Timer 1 CC2 event
0010: Timer 1 CC3 event
0011: Timer 2 CC2 event
0100: Timer 2 CC3 event
0101: Timer 2 CC4 event
0110: Timer 2 TRGO event
0111: Timer 3 CC1 event
1000: Timer 3 TRGO event
1001: Timer 4 CC4 event
1010: Timer 5 CC1 event
1011: Timer 5 CC2 event
1100: Timer 5 CC3 event
1101: Timer 8 CC1 event
1110: Timer 8 TRGO event
1111: EXTI line 11

## different than other adc_v2_multi
[STM32F730 ](https://www.st.com/resource/en/reference_manual/rm0431-stm32f72xxx-and-stm32f73xxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf#page=408)
[STM32F745 STM32F750](https://www.st.com/resource/en/reference_manual/rm0385-stm32f75xxx-and-stm32f74xxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf#page=446)
[STM32F765](https://www.st.com/resource/en/reference_manual/dm00224583-stm32f76xxx-and-stm32f77xxx-advanced-arm-based-32-bit-mcus-stmicroelectronics.pdf#page=471)

0000: Timer 1 CH1 
0001: Timer 1 CH2 
0010: Timer 1 CH3 
0011: Timer 2 CH2 
0100: Timer 5 TRGO 
0101: Timer 4 CH4 
0110: Timer 3 CH4 
0111: Timer 8 TRGO 
1000: Timer 8 TRGO(2) 
1001: Timer 1 TRGO 
1010: Timer 1 TRGO(2) 
1011: Timer 2 TRGO 
1100: Timer 4 TRGO 
1101: Timer 6 TRGO 
1110: Reserved
1111: EXTI line11

## stm32f7x[2367]
I don't know how these should be categorized. 

So for the next steps should these be broken into a new child YAML or added as exceptions to existing ones?

**Comment by taylorh140** [comment]
|                |       EXTSEL SET A      |       EXTSEL SET B       |       EXTSEL SET C       |      EXTSEL SET D     |
|----------------|:-----------------------:|:------------------------:|:------------------------:|:---------------------:|
| adc_v2:        |                         | STM32F411                |                          |                       |
| adc_v2:        |                         | STM32f401                |                          |                       |
| adc_v2_single: | STM32410                |                          | STM32F412                |                       |
| adc_v2_single: |                         |                          | STM32F413                |                       |
| adc_v2_multi:  |                         |                          | STM32F205                |                       |
| adc_v2_multi:  |                         |                          | STM32F207                |                       |
| adc_v2_multi:  |                         |                          | STM32F405                |                       |
| adc_v2_multi:  |                         |                          | STM32F407                |                       |
| adc_v2_multi:  |                         |                          | STM32F427                |                       |
| adc_v2_multi:  |                         |                          | STM32F429                |                       |
| adc_v2_multi:  |                         |                          | STM32F446                |                       |
| adc_v2_multi:  |                         |                          | STM32F469                |                       |
| adc_v2_multi:  |                         |                          |                          | STM32F730             |
| adc_v2_multi:  |                         |                          |                          | STM32F745             |
| adc_v2_multi:  |                         |                          |                          | STM32F750             |
| adc_v2_multi:  |                         |                          |                          | STM32F765             |
|                |       EXTSEL SET A      |       EXTSEL SET B       |       EXTSEL SET C       |      EXTSEL SET D     |
|                | 0000: Timer 1 CC1 event | 0000: Timer 1 CC1 event  | 0000: Timer 1 CC1 event  | 0000: Timer 1 CH1     |
|                | 0001: Timer 1 CC2 event | 0001: Timer 1 CC2 event  | 0001: Timer 1 CC2 event  | 0001: Timer 1 CH2     |
|                | 0010: Timer 1 CC3 event | 0010: Timer 1 CC3 event  | 0010: Timer 1 CC3 event  | 0010: Timer 1 CH3     |
|                | 0011: Reserved          | 0011: Timer 2 CC2 event  | 0011: Timer 2 CC2 event  | 0011: Timer 2 CH2     |
|                | 0100: Reserved          | 0100: Timer 2 CC3 event  | 0100: Timer 2 CC3 event  | 0100: Timer 5 TRGO    |
|                | 0101: Reserved          | 0101: Timer 2 CC4 event  | 0101: Timer 2 CC4 event  | 0101: Timer 4 CH4     |
|                | 0110: Reserved          | 0110: Timer 2 TRGO event | 0110: Timer 2 TRGO event | 0110: Timer 3 CH4     |
|                | 0111: Reserved          | 0111: Timer 3 CC1 event  | 0111: Timer 3 CC1 event  | 0111: Timer 8 TRGO    |
|                | 1000: Reserved          | 1000: Timer 3 TRGO event | 1000: Timer 3 TRGO event | 1000: Timer 8 TRGO(2) |
|                | 1001: Reserved          | 1001: Timer 4 CC4 event  | 1001: Timer 4 CC4 event  | 1001: Timer 1 TRGO    |
|                | 1010: Timer 5 CC1 event | 1010: Timer 5 CC1 event  | 1010: Timer 5 CC1 event  | 1010: Timer 1 TRGO(2) |
|                | 1011: Timer 5 CC2 event | 1011: Timer 5 CC2 event  | 1011: Timer 5 CC2 event  | 1011: Timer 2 TRGO    |
|                | 1100: Timer 5 CC3 event | 1100: Timer 5 CC3 event  | 1100: Timer 5 CC3 event  | 1100: Timer 4 TRGO    |
|                | 1101: Reserved          | 1101: Reserved           | 1101: Timer 8 CC1 event  | 1101: Timer 6 TRGO    |
|                | 1110: Reserved          | 1110: Reserved           | 1110: Timer 8 TRGO event | 1110: Reserved        |
|                | 1111: EXTI line 11      | 1111: EXTI line11        | 1111: EXTI line 11       | 1111: EXTI line11     |


Given the table above it looks like there should be some YAML file that configures for each set of devices

inhertance:
adc_v2_extsel_a.yaml <- adc_v2_extsel_b.yaml <- adc_v2_extsel_c.yaml

and a one off:
adc_v2_extsel_d.yaml

**Comment by burrbull** [comment]
Just remove EXTSEL from adc_v2.yaml, create different files for each set of EXTSEL and include them directly in device files.

**Comment by taylorh140** [comment]
Well, it took a second but that should have most of the details handled. this added a new subfolder for the 4 different configurations.

**Comment by taylorh140** [comment]
Just so it's clear is there anything else I need to do for this, or am I just waiting for review? Who reviews stuff/how does that work?

**Comment by newAM** [comment]
I rebased to get a fresh memmap comparison, then added some minor white-space fixes as well.  I checked all the changes (thanks for the links to the reference manuals!), looks good to me.

Let me know if you're ok with my edits (trimmed trailing whitespace in `adc_v2_extsel_d.yaml`) and I'll merge this.

**Review by taylorh140 — COMMENTED** [review]
found a few places where the spacing after EXTI line was missing. Looks good other than that

**Review by newAM — APPROVED** [review]
Thanks for the changes and breaking all of it down for easy review!

bors r+

**Pull request merged**
