### PR TITLE
Use cortex-m latest 0.6.0

### PR DESCRIPTION
**Pull request by mathk**
This might also require a version change of all sub component. Let me know.

### CODE REVIEW

**Comment by adamgreig** [comment]
Thanks! This will require a version bump but we'll do that at release, it doesn't need to be in the PR.

However I'd like to support cortex-m version `">0.5.8,<0.7"` to allow people to use the stm32-rs crates with 0.5.8 _and_ 0.6, since at the moment we'd be completely compatible with both and it helps prevent splitting the ecosystem. Could you update the PR for that please?

**Comment by mathk** [comment]
Done with ">=0.5.8,<0.7"

**Comment by adamgreig** [comment]
Sorry, I should have noticed this the first time.. you also need to make the change in `makecrates.py`

https://github.com/stm32-rs/stm32-rs/blob/master/scripts/makecrates.py#L51

which is what generates the `Cargo.toml` files for each crate, otherwise these changes would get blown away next time.

**Comment by mathk** [comment]
> Sorry, I should have noticed this the first time.. you also need to make the change in `makecrates.py`
> 
> https://github.com/stm32-rs/stm32-rs/blob/master/scripts/makecrates.py#L51
> 
> which is what generates the `Cargo.toml` files for each crate, otherwise these changes would get blown away next time.

Done

**Comment by adamgreig** [comment]
Thanks!

**Pull request merged**
