### PR TITLE
xmlformat

### PR DESCRIPTION
**Pull request by burrbull**
Format patched svds with `xmllint --format`

### CODE REVIEW

**Comment by adamgreig** [comment]
I like the idea of this a lot, but I'm not sure how much it will change the existing SVD content, making it harder to diff the patched/unpatched SVDs. Not that it's especially easy already... Any idea how much this changes the stock parts of the SVD? I wonder if the Python XML writer can be made to tidy the output instead.

**Comment by burrbull** [comment]
On the contrary, it simplifies the comparison and verification of the result. I used it many times with SVD and never had problems or lost data.

**Comment by adamgreig** [comment]
Do you mean running it on the stock SVD files does not change them, or do you run it on both before comparing?

**Comment by burrbull** [comment]
I ran it on patched files. But we can add this into `extract` script to check stock SVDs also.

**Comment by burrbull** [comment]
Or I can separate it in additional instruction in Makefile, like:
`make svdformat`

**Comment by aurelj** [comment]
This would indeed be a very useful feature to compare SVDs, but it wouldn't be useful for someone who only want to generate the final crates.
So I think that adding a new instruction in the Makefile that would format both the original SVD and the patched one would be a great solution. Something like:
`make xmlformat`

**Comment by burrbull** [comment]
I've tried to create separate command `svdformat`, but I'm not sure I do all right.
I'm ignoramus in makefiles.

**Comment by adamgreig** [comment]
I've merged these along with a change to the Makefile so it outputs `%.svd.patched` alongside the other SVDs, which I think is cleaner but still serves the same purpose.

**Pull request merged**
