### PR TITLE
ci: fix tool install for nightlies

### PR DESCRIPTION
**Pull request by newAM**
Follow up to #756 and #758

### CODE REVIEW

**Comment by burrbull** [comment]
cc @adamgreig

**Comment by adamgreig** [comment]
Can we just run `tool_install.sh` without any arguments, then it installs all three, right?

**Comment by burrbull** [comment]
> 

Yes

**Comment by newAM** [comment]
Good catch, fixed & rebased.

**Review by adamgreig — APPROVED** [review]
bors r+

**Pull request merged**
