### PR TITLE
Implement initial support for STM32L4P5 (and therefore STM32L4Q5)

### PR DESCRIPTION
**Pull request by FerdinandvHagen**
This pull request adds initial support for STM32L4P5 (and therefore STM32L4Q5).
It replaces Pull Request #773 which contained merges.

Done:
- Mmaps compared to reference manual revision 9 (should fully match now)
- Enumerated values added where available / possible

Known issues:
- few peripherals missing (most notably TAMPER peripheral).

As this is quite a lot of patches and also new enumerated values I would kindly ask for feedback in case things should be organized differently.

### CODE REVIEW

**Comment by FerdinandvHagen** [comment]
@adamgreig @burrbull Any chances to merge this?

**Review by newAM — APPROVED** [review]
RM link for anyone else who wants to review: https://www.st.com/resource/en/reference_manual/rm0432-stm32l4-series-advanced-armbased-32bit-mcus-stmicroelectronics.pdf

This is a big one, I didn't check it all, but the parts I did check were all correct (at least as far as I could tell, the firewall is strange).

I'll give it a day and merge it tomorrow if no other reviews come in.

**Comment by burrbull** [comment]
bors r=@newAM

**Comment by FerdinandvHagen** [comment]
Thank you so much @newAM!

I'm gonna test it anyways in the weeks coming up so if any issues pop up I will do another pull request.
The RM is pretty bad in some parts. Firewall I never used myself so sometimes it was a guessing game what the RM means...

**Pull request merged**
