### PR TITLE
Clusters and arrays for f103

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
Now svd2rust can't handle arrays with dimension 1.
But before it could.
Sometimes this is useful.

**Comment by burrbull** [comment]
Closes #56 .

**Comment by adamgreig** [comment]
Does svd2rust process clusters?

**Comment by adamgreig** [comment]
Thanks for adding these features! I'm glad to get them into the upcoming release.

**Pull request merged**
