### PR TITLE
[timers] make TIM3/4 16-bit and some definitions

### PR DESCRIPTION
**Pull request by richardeoin**
* Where TIM3 was `derivedFrom` 32-bit timer TIM2, `_copy` it and use
  correct 16-bit ranges for `CNT` rather than incorrect 32-bit
* Add some definitions specific to Advanced-control timers TIM1/TIM8,
  in the `BDTR` register
* `OCxPE` definitions (`CCMR` output preload)

### CODE REVIEW

**Comment by burrbull** [comment]
Closes #147, #132 .

**Comment by richardeoin** [comment]
I've run `cargo check` with this PR on the following HAL crates, with no errors.

stm32f3xx-hal
stm32l0xx-hal
stm32l4xx-hal
stm32f1xx-hal
stm32f0xx-hal
stm32f4xx-hal

These crates are accessing the whole register in an `unsafe` block eg.
```rust
tim.arr.write(|w| unsafe { w.bits(cast::u32(arr)) });
```

Therefore changing the size of the field doesn't break these crates.

Thoughts @adamgreig ? I'm happy to scale back the changes if this PR is too much.

**Comment by adamgreig** [comment]
Thanks for checking them! I'm happy with the PR, just need a bit more time to review it properly. I think it's close to time for another release so I'll try and get pending PRs cleared and look to release this weekend or early next week.

**Comment by adamgreig** [comment]
Thanks for this PR! The timers are one of the biggest pains to get right across all the devices, I think.

I'm happy with all the contents but ideally the SVD modifications would go into `common_patches/` leaving just the enumeration descriptions in `peripherals/`. That said, in this case it might be less elegant since you've nicely factored out the various `_mixed`/`_16bit` and `_l` options. What do you think? I could be convinced to merge this as-is but if you think it would be easy enough to split into patches vs peripheral descriptions that would be nice.

**Comment by richardeoin** [comment]
Sure, refactoring into `common_patches/` is preferable and wasn't too difficult. Thanks to `M-x dired-do-query-replace-regexp` for the heavy lifting :-)

It does mean there's two trees mapping `tim2345.*` to `tim2_common_.*`, but the mapping in `peripherals/` is simplified as there's no need for `_l` there.

**Pull request merged**
