### PR TITLE
stm32h7: add cluster for MDMA registers

### PR DESCRIPTION
**Pull request by richardeoin**
This applies ok with the current svdtools (`svd patch`), but https://github.com/stm32-rs/svdtools/pull/42 is needed to correctly identify the dimIndex. 

For current svdtools, because `spec_ind()` prefers `?` to `[..]`, placing the `?` pattern after the comma means that `rname[li : len(rname) - ri]` is always `""`. At least that's reasonably neat.

### CODE REVIEW

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
bors try

**Comment by adamgreig** [comment]
This looks good and I've now released svdtools 0.1.10 that includes your fix there too. The only thing I noticed is that previously the ISR and IFCR registers had fields like `TEIF4` where now they're all `TIEF0`. Maybe we should rename them to just `TIEF` so the ones for e.g. channel 4 don't say 0?

**Comment by richardeoin** [comment]
Thanks for the release!

**Review by adamgreig — APPROVED** [review]
Thanks!

bors merge

**Pull request merged**
