### PR TITLE
Add missing interrupts for USART

### PR DESCRIPTION
**Pull request by aurabindo**
Signed-off-by: Aurabindo Pillai <mail@aurabindo.in>

### CODE REVIEW

**Comment by aurabindo** [comment]
sure, I can do that. One of those is a uart interrupt which I should add after this patch is landed. CI is taking forever?

**Comment by adamgreig** [comment]
Yea, it looks like something's up with bors perhaps, as the actual builds on Travis seem fine. I'll check again tomorrow.

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
Ok, I think I've fixed it...

bors retry

**Pull request merged**
