### PR TITLE
Fix address offsets on H743/V DFSDM

### PR DESCRIPTION
**Pull request by David-OConnor**
Addresses #636

### CODE REVIEW

**Comment by adamgreig** [comment]
It looks like only the 743/743v use the names you've got in the file, the other H7 series use names either without the DFSDM prefix for the common registers like `CH0CFGR1`, or with it for the filter block ones like `DFSDM_FLT0CR1`. What a pain! I think the patch file you've got now is good for the 743/743v, but the other H7s probably just need the `_strip: DFSDM` alone and I don't think anything else?

**Comment by David-OConnor** [comment]
Done: Strip for non-H743. Redo names/offsets for 743/V

**Comment by adamgreig** [comment]
Thanks for this PR! I've updated it a bit to get cluster support too.

Getting clusters to work was a pain because of a few more weird inconsistencies (how on _earth_ did they end up with `FLT1CHGR` when all the other FLTs are `FLTxJCHGR`???). In the end it seemed best to split it into separate files for 7B3, 743, and 735/47/53.

The downside is that the clusters do not form arrays because there is a gap between each cluster element, and svd2rust 0.19 cannot turn that into an array - it can't add padding because the padding might overlap over registers (though not in this case), and a recent PR to use an array proxy in this case hasn't been released yet (see https://github.com/rust-embedded/svd2rust/pull/531 and https://github.com/rust-embedded/svd2rust/pull/534).

Anyway, they are at least the same _type_, and in future will probably get arrayified.

**Review by adamgreig — APPROVED** [review]
bors merge

**Pull request merged**
