### PR TITLE
Use wildcard in bors.toml instead of specifying each build

### PR DESCRIPTION
**Pull request by therealprof**
According to the bors documentation SQL-like wildcards are allowed

### CODE REVIEW

**Comment by adamgreig** [comment]
Aah, this would be much better.

bors try

**Comment by adamgreig** [comment]
Looks like the whole build now succeeds after any one success, without knowing it has to wait for the rest of them...

**Comment by therealprof** [comment]
Weird.

**Comment by therealprof** [comment]
Hm, there's an RFC for a new variable to wait until those checks have been completed: https://bors.tech/rfcs/0360-add-a-new-configuration-option-status-wait-success.html

Not sure whether this is available already, though.

**Comment by therealprof** [comment]
bors try

**Comment by adamgreig** [comment]
bors try

**Comment by adamgreig** [comment]
It looks like that bors RFC addresses a slightly different need, when there are checks that start out failing and then turn green within the timeout period. For this GHA case, the extra checks are simply not reported to Travis at all, it doesn't know they will occur until they complete. We don't want it to always wait 1h to see what might appear, so I think we just have to enumerate all the checks.

**Comment by therealprof** [comment]
The way I'm reading it the "status" is used for quick failing and the "status_wait_success" for the unblocking.

That's super-weird; why would you have wildcard support if it means "any" of the matches instead of "all" of the matches?

**Comment by therealprof** [comment]
Anyway, let's close this then.

**Pull request closed without merging**
