### PR TITLE
bump svd2rust to 0.20

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Review by newAM — CHANGES_REQUESTED** [review]
README needs to be updated for the new version

**Comment by burrbull** [comment]
> README needs to be updated for the new version

It is not new version. It is dependency.

**Comment by newAM** [comment]
Sorry, I should be more clear, I mean the version in the "building locally" instructions in the README:

https://github.com/stm32-rs/stm32-rs/blob/a2b00722dba5d3511c76f092e8d6d0bb2cf2c62f/README.md?plain=1#L93

**Comment by burrbull** [comment]
> Sorry, I should be more clear, I mean the version in the "building locally" instructions in the README:
> 
> https://github.com/stm32-rs/stm32-rs/blob/a2b00722dba5d3511c76f092e8d6d0bb2cf2c62f/README.md#L93

Fixed. Thanks

**Review by newAM — APPROVED** [review]

**Comment by burrbull** [comment]
bors r=newAM

**Review by adamgreig — APPROVED** [review]
bors r+

**Pull request merged**
