### PR TITLE
Fix name of bit fields LPVAE and LPHFPE in DSIHOST VMCR for STM32F469

### PR DESCRIPTION
**Pull request by Jsbjr**

### CODE REVIEW

**Comment by burrbull** [comment]
What about change it to:
```yaml
DSIHOST:
  _strip:
    - "DSI_"
  VMCR:
    _modify:
      LVAE:
        name: LPVAE
      LPHFE:
        name: LPHFPE
```

This will remove unneeded "DSI_" prefix from all registers.

**Comment by Jsbjr** [comment]
Striping DSI_ would make sense.
This appear in all those files:
```
svd/stm32mp157.svd.patched
svd/stm32wb55.svd.patched
svd/stm32l4r9.svd.patched
svd/stm32h747cm7.svd.patched
svd/stm32h743v.svd.patched
svd/stm32h7b3.svd.patched
svd/stm32h743.svd.patched
svd/stm32g081.svd.patched
svd/stm32h753v.svd.patched
svd/stm32h753.svd.patched
svd/stm32g071.svd.patched
svd/stm32g070.svd.patched
svd/stm32h747cm4.svd.patched
svd/stm32g041.svd.patched
svd/stm32g030.svd.patched
svd/stm32g031.svd.patched
svd/stm32f7x9.svd.patched
svd/stm32f7x7.svd.patched
svd/stm32f765.svd.patched
svd/stm32f745.svd.patched
svd/stm32f469.svd.patched
```
If it is done it is probably nicer to do it on all those devices

**Comment by burrbull** [comment]
Then place this patch in separate file in `common_patches` and include it from all these device yaml's.

**Comment by Jsbjr** [comment]
Actually there are not that much DSI modules as I expected.
I had lots of false positives, searching for the DSI_ prefix was not spot on.
Now I'm not sure if 5 files is a common enough occurrence to justify a common patch script.

**Comment by burrbull** [comment]
cc @adamgreig

**Comment by adamgreig** [comment]
@burrbull is this now done by #540?

**Comment by burrbull** [comment]
Partially as I can see.

**Comment by adamgreig** [comment]
Closed by #585, thanks @Jsbjr!

**Pull request closed without merging**
