### PR TITLE
clear all vendor provided enumeratedValues for g0 and h7b3

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Comment by burrbull** [comment]
Strange changes in mmaps for h7x3

**Comment by burrbull** [comment]
> Strange changes in mmaps for h7x3

Looks unrelated to this PR.

**Comment by burrbull** [comment]
Rebased on master

**Review by adamgreig — APPROVED** [review]
Thanks!

Just for my future reference: this PR clears fields from every used SVD that comes with ST enumeratedValues, so no other SVDs are affected by removing the clears from the shared patches, and every ST provided enumeration is removed.

bors merge

**Pull request merged**
