### PR TITLE
Hrtim #1021

### PR DESCRIPTION
**Pull request by usbalbin**
Hrtim #1021

### CODE REVIEW

**Comment by usbalbin** [comment]
Here @burrbull

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
@usbalbin Thanks.
What do you think. Is it make sense to remove timer block suffix from register names?
`CMP1xR (RM) => CMP1AR, CMP1BR (SVD now) => CMP1R`

**Comment by usbalbin** [comment]
No problem

While it is a slight diviation from the reference manual, I don't think there is any ambiguity and the HAL implementations will be a lot cleaner having the same name for all timers.

So sure why not

**Comment by usbalbin** [comment]
(Disclaimer, not sure if there is any prior art for other peripherals)

**Comment by burrbull** [comment]
> What do you think. Is it make sense to remove timer block suffix from register names?

Make PR from [hrtim-strip](https://github.com/stm32-rs/stm32-rs/tree/hrtim-strip) branch, please.

**Pull request merged**
