### PR TITLE
stm32f411 otg fixes

### PR DESCRIPTION
**Pull request by Windfisch**
Hi, these are some issues I noticed when I was developing my usb host crate for the stm32f411.

### CODE REVIEW

**Comment by Windfisch** [comment]
@burrbull do you have some time for a review :)?

**Comment by burrbull** [comment]
> @burrbull do you have some time for a review :)?

I don't have write access to this repo. Ask @adamgreig

**Comment by Windfisch** [comment]
oh. sorry. yea, @adamgreig, do you have some spare time for this?

**Comment by Windfisch** [comment]
@adamgreig or @newAM, could you please review this?

**Review by newAM — APPROVED** [review]
I double checked the changes against [RM0383 Rev 3](https://www.st.com/resource/en/reference_manual/rm0383-stm32f411xce-advanced-armbased-32bit-mcus-stmicroelectronics.pdf), looks good to me, thanks for the fixes!

I do have write access to the repo, but I was given write access for STM32WL pull-requests, I'll ask @adamgreig about merging PRs for other chips.

**Comment by Windfisch** [comment]
thanks @newAM :)

**Pull request merged**
