### PR TITLE
update stm32f4 sources (v2.0)

### PR DESCRIPTION
**Pull request by burrbull**
See #877

### CODE REVIEW

**Comment by burrbull** [comment]
cc @adamgreig This is also ready for review. mmaps needs manual run.

**Comment by burrbull** [comment]
rebased

**Comment by adamgreig** [comment]
I think the `.orig` files shouldn't be in the commit?

**Comment by burrbull** [comment]
> I think the `.orig` files shouldn't be in the commit?

Rebasing artifacts. Fixed.

**Pull request closed without merging**
