### PR TITLE
Add cargo build support

### PR DESCRIPTION
**Pull request by tones111**
This change adds a cargo build script to allow dependent crates to specify stm32 as a Cargo.toml dependency.  Cargo can also be used to build within the repository with something like...
cargo build --features 'rt stm32f303'

It does depend on a svd2rust PR
https://github.com/japaric/svd2rust/pull/202

This support only allows one device feature to be specified (otherwise duplicate statics prevent compilation).  The build.rs script will panic if it detects too many devices.

### CODE REVIEW

**Comment by tones111** [comment]
This PR has been updated to not generate internal modules since only one device feature is allowed at a time.  Clippy build.rs support has been added and assiciated fixes made.  The svd2rust dependency has now been internalized so the user no longer needs it in their path.

The only external dependency to build is the nightly version of rustfmt.

**Comment by tones111** [comment]
With https://github.com/rust-embedded/svd2rust/pull/267 landing, I've brushed off some of the dust from this effort.  Hopefully this simplifies crate maintenance and makes downstream usage more consistent.

**Comment by tones111** [comment]
Pinging @adamgreig for another look please.  Thanks.

**Comment by tones111** [comment]
Pinging @adamgreig for feedback on this changeset please.

**Comment by gkelly** [comment]
I think this is a useful change, especially for users at the bleeding edge who want to use devices not yet in releases (stm32f730 in my case) who then need to clone and follow build instructions and then reference the crate locally instead of just having `stm32f7 = {git ...` as a dependency.

**Comment by adamgreig** [comment]
After a lot of thinking about this I've decided to not include it in stm32-rs. I don't think having end users generate the modified SVD, then generate the PAC, and then finally build it is the way to go. We've got the crates.io builds for most users, and the new [stm32-rs nightlies](https://github.com/stm32-rs/stm32-rs-nightlies) which should allow using the latest master as a git dependency, so I think most use cases are covered.

Thank you regardless for putting the PR together, and apologies that it's taken almost two years to decide!

**Pull request closed without merging**
