### PR TITLE
Add stm32l4r5

### PR DESCRIPTION
**Pull request by gauteh**
- add stm32l4r5 device
- rename CH7WDATR (the second) to CH7DATINR
- l4r5: copy ADC1 from l4x5

### CODE REVIEW

**Comment by adamgreig** [comment]
So far this looks pretty reasonable to me, let me know if you have any questions or any problems as you get it ready!

**Comment by gauteh** [comment]
Thanks, I think it is good, I'll do a bit more testing and report back. But should otherwise be ready (for review) from my side.

**Comment by gauteh** [comment]
Ok, I think the easiest is to go with ADC1 for the peripheral. The interrupt is already named ADC1. But it would make it more consistent to rename the ADC on the r9 to ADC1 as well (@jspngh might have objections to that).

**Comment by jspngh** [comment]
I have no problem with renaming it to `ADC1` for all L4+ devices

**Comment by gauteh** [comment]
Hi, I know you are all busy. I think this one is ready if you have the chance to look at it. Thanks, Gaute

**Review by richardeoin — COMMENTED** [review]
I suspect in general we should prefer to merge PRs like this, and fix errors later. But I did find a few items to fix - and might apply to other L4 parts also.

Reference manual: RM0432 rev 9

* ADC3 interrupt when there's no adc3 peripheral, should be deleted. It's under ADC1 in the SVD, so you can fix it with something like:
```yaml
ADC1:
  _delete:
    _interrupts:
      - ADC3
```
* TIM1/8 `OR1` registers both have a field `ETR_ADC3_RMP` that doesn't exist in the RM.
* TIM1/8 `OR1` register description is wrong
* `OSPI1` bits are missing from RCC `AHB3ENR` `AHB3RSTR` `AHB3SMENR` (at least some R5 parts have two octospi, although it is hard to tell sometimes)
* RCC `CFGR` -> `MCOSEL` is 3 bits wide, should be 4 (and there is a code `1000` that's used for the HSI48)
* RCC missing `DLYCFGR` register
* PWR missing `PDCRI` `PUCRI` `CR5` registers
* Flash `ACR` -> `LATENCY` is 3 bits wide, should be 4
* Flash `SR` missing `PEMPTY` bit
* Flash `ECCR` bit broken, `ADDR_ECC` is too small and then `BK_ECC` `SYSF_ECC` at the wrong offsets
* Flash missing `CFGR` register

**Comment by richardeoin** [comment]
Also a missing register on LPUART1: https://github.com/stm32-rs/stm32-rs/issues/694

**Comment by richardeoin** [comment]
@gauteh Do you plan to respond to the review feedback in this PR? This part does look like a useful one to support

**Comment by gauteh** [comment]
Hi, to be honest I don't know when I will have time to look into it. It all
seems sensible.

søn. 15. mai 2022, 13:25 skrev Richard Meadows ***@***.***>:

**Comment by richardeoin** [comment]
Closed with #740 🎉

**Pull request closed without merging**
