### PR TITLE
Initial support for STM32L4P5 (and therefore STM32L4Q5)

### PR DESCRIPTION
**Pull request by FerdinandvHagen**
This pull request adds initial support for STM32L4P5 (and therefore STM32L4Q5).

Done:
- Mmaps compared to reference manual revision 9 (should fully match now)
- Enumerated values added where available / possible

Known issues:
- few peripherals missing (most notably TAMPER peripheral)
- some registers / fields currently not named correctly

Will try to fix the register / field names in the next couple of days.
As this is quite a lot of patches and also new enumerated values I would kindly ask for feedback in case things should be organized differently.

### CODE REVIEW

**Comment by FerdinandvHagen** [comment]
Thank you very much @burrbull for the feedback.
Should be now in sync with master and also fixed some bugs found through CI.

**Comment by adamgreig** [comment]
thank you, this looks great! do you want to fix up the missing descriptions etc in this PR, or get it merged and do fixes later?

**Comment by burrbull** [comment]
Don't do `merge` in PR. Use `rebase` instead.

**Comment by FerdinandvHagen** [comment]
@adamgreig Descriptions are added now. So that is good to go.

@burrbull Sorry for that! Any way to solve it (changing multiple commits + 2 merges to a rebase). Used to just squashing everything in Gitlab where this is not an issue usually.

**Comment by FerdinandvHagen** [comment]
Closing in favor of Pull Request #781 to eliminate the issue with branch merges.

**Pull request closed without merging**
