### PR TITLE
minor fix ('make patch' did not work)

### PR DESCRIPTION
**Pull request by torkeldanielsson**
`make patch` did not work for me, complaining about description of STALL. This PR solved it for me.

(Or is it some compat issue? I'm on Windows, x64, python 3.7.)

### CODE REVIEW

**Comment by adamgreig** [comment]
That's pretty weird. All the commits are tested in CI and that one's been there for months, so I'm guessing it's something unusual on your setup, but I can't imagine what. Could you possibly paste the full error you got?

**Comment by torkeldanielsson** [comment]
Yes, it's weird!

Below is the error in full, including some versions of things. Shell is the 'git for windows' bash shell. Windows is probably not the regular dev environment, but why would this specific thing cause an issue?

> torke@DESKTOP-KNQQR04 MINGW64 /c/dev/stm32-rs (master)
> $ python3 --version
> Python 3.7.3
> $ /c/Qt/Tools/mingw730_64/bin/mingw32-make.exe --version
> GNU Make 4.2.1
> $ /c/Qt/Tools/mingw730_64/bin/mingw32-make.exe patch
> python3 scripts/makedeps.py devices/stm32f427.yaml > .deps/stm32f427.d
> python3 scripts/makedeps.py devices/stm32f429.yaml > .deps/stm32f429.d
> python3 scripts/makedeps.py devices/stm32f446.yaml > .deps/stm32f446.d
> python3 scripts/makedeps.py devices/stm32f407.yaml > .deps/stm32f407.d
> svd patch devices/stm32f429.yaml
> Traceback (most recent call last):
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\patch.py", line 823, in modify_field
>     ftag.find(key).text = str(value)
> AttributeError: 'NoneType' object has no attribute 'text'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\Scripts\svd.exe\__main__.py", line 9, in <module>
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\click\core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\cli.py", line 16, in patch
>     svdtools.patch.main(yaml_file)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\patch.py", line 1025, in main
>     process_device(svd, root)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\patch.py", line 1005, in process_device
>     d.process_peripheral(periphspec, device[periphspec], update_fields)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\patch.py", line 434, in process_peripheral
>     p.process_register(rspec, register, update_fields)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\patch.py", line 752, in process_register
>     r.modify_field(fspec, fmod)
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\patch.py", line 827, in modify_field
>     key, self.rtag.find("name").text, ftag.find("name").text
> svdtools.patch.SvdPatchError: invalid attribute 'description' for register DOEPCTL4, field STALL
> mingw32-make: *** [Makefile:39: svd/stm32f429.svd.patched] Error 1

**Comment by adamgreig** [comment]
I still can't make heads or tails of this. Could you try a clean checkout just in case there's some gremlin? Also, could you try making each of these SVDs individually and see if they _all _ have the error or only some of them?

```
make svd/stm32f427.svd.patched
make svd/stm32f429.svd.patched
make svd/stm32f405.svd.patched
make svd/stm32f407.svd.patched
make svd/stm32f446.svd.patched
```

I've had a look and I can't see any surprise non-ASCII glitches in the yaml or svd files, and all the `Stall` fields already do have `description` fields which is the only other reason I can see that error coming about.

**Comment by torkeldanielsson** [comment]
It still fails on a clean checkout:

> $ git clone git@github.com:stm32-rs/stm32-rs.git stm32-rs_clean
> [...cut...]
> $ cd stm32-rs_clean/
> $ cd svd; ./extract.sh; cd ..
> Archive:  vendor/en.stm32f0_svd.zip
>   inflating: stm32f0x0.svd
> [...cut...]
> $ /c/Qt/Tools/mingw730_64/bin/mingw32-make.exe -j 8 patch
> [...cut...]
>   File "C:\Users\torke\AppData\Roaming\Python\Python37\site-packages\svdtools\patch.py", line 827, in modify_field
>     key, self.rtag.find("name").text, ftag.find("name").text
> svdtools.patch.SvdPatchError: invalid attribute 'description' for register DOEPCTL4, field STALL
> mingw32-make: *** [Makefile:39: svd/stm32f427.svd.patched] Error 1
 (cut out most of it but point is it still fails)

All of the individual tests on your list fails.
I also did the Windows thing and tried it again after a reboot - same story.

I did see something curious now - the failure log for stm32f407 is "svdtools.patch.SvdPatchError: invalid attribute 'description' for register DOEPCTL4, field STALL". But I can only find up to DOEPCTL3 in the svd. Maybe there's a clue there? I grep:ed for DOEPCTL in the repo and saw some different ways it is used, but I don't understand the .yaml file format well enough to spot errors..

**Comment by adamgreig** [comment]
That might be a clue... in a python shell, could you try this?

```python
>>> from fnmatch import fnmatch
>>> fnmatch("STALL", "Stall")
False
```

**Comment by adamgreig** [comment]
DOEPCTL4 and 5 are created by a patch, which creates them with the stall field named `STALL`. The SVD provided fields are named `Stall`, so a different patch renames those to `STALL` and updates their description. However, that second patch was incorrectly matching against the new `STALL` fields on Windows because Windows is case-insensitive in filenames, and then failed to modify the non-existent `description` attribute of the new field. I've filed a PR against svdtools to always use a case-sensitive comparison.

If you wanted, changing otg_hs_fixes_v1.yaml so that when it adds the new `STALL` field it also sets its description should fix the issue too, i.e.

```yaml
STALL:
  bitOffset: 21
  bitWidth: 1
  access: read-write
  description: STALL handshake
```

You could probably put that in this PR, check it builds, and I could merge it to at least fix the issue for now.

**Comment by torkeldanielsson** [comment]
Wow - nice job debugging that!! 

PR is updated and it works now on my machine :)

**Pull request merged**
