### PR TITLE
Add devices/stm32g491.yaml

### PR DESCRIPTION
**Pull request by pawelchcki**
This is a companion PR to https://github.com/stm32-rs/stm32-rs/pull/488 which should be merged first.

Otherwise the CI mmap checker breaks, on missing vendor svd file for `stm32g491` in master

### CODE REVIEW

**Comment by pawelchcki** [comment]
Sorry for creating so many PR's, just want to make the review process smooth :)

**Comment by adamgreig** [comment]
No problem, thanks for all the work! I'll try to get these reviewed in the next few days.

**Comment by adamgreig** [comment]
Thanks a lot for this and #488! I've merged both commits in #492 along with a few other tweaks for the new SVD file.

**Comment by pawelchcki** [comment]
Thanks !! :)

**Pull request merged**
