### PR TITLE
Add stm32g070 and stm32g071 to replace stm32g07x

### PR DESCRIPTION
**Pull request by ijager**
The main goal of this PR is to create separate crates for `stm32g070` and `stm32g071` since the `g070` belongs to the value line that is missing a lot of features compared to the 'access line'. 

I extracted the latest SVD files from STM32CubeIDE. They're a bit better than previous version, still quite some bugs in the files for parts other than G081 (since it is the part with all features). However the bugs are mostly peripherals that actually don't exist on that specific part. I manually edited the SVD files for G071 and G070 to remove some of those. 

This addresses https://github.com/stm32-rs/stm32-rs/issues/394 and is related to https://github.com/stm32-rs/stm32g0xx-hal/issues/18

### CODE REVIEW

**Comment by adamgreig** [comment]
Thanks for the update! I think it does make sense to split the 70/71 apart.

> I manually edited the SVD files for G071 and G070 to remove some of those.

We only put completely stock unmodified SVDs in the zip files; ideally these zip files should be directly downloaded from ST and not modified at all. Would it be possible to redo your modifications as patches in the device YAML files or in `common_patches/` please?

**Comment by ijager** [comment]
Ok I see. It is gonna take way more time then to do. I can revert to the stock files, but the stock ST version literally has typos:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: In peripheral `ADC`

Caused by:
    0: In register `HWCFGR6`
    1: 0x1F1F1F11F invalid
    2: number too large to fit in target type', /Users/ingmar/.cargo/registry/src/github.com-1ecc6299db9ec823/svd2rust-0.17.0/src/main.rs:96:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [stm32g0/src/stm32g070/mod.rs] Error 101
```

So I fix that now with a patch and then in the next revision ST also fixes it and then we undo the patch again? Or can svdtools/svd2rust ignore those cases then?

**Comment by ijager** [comment]
Now it contains the stock SVD files v1.3 with a patch to make it build. The other changes I might add back later with patches, it is a different issue anyway.

**Comment by ijager** [comment]
@adamgreig, anything else I should change?

**Pull request merged**
