### PR TITLE
ci: fix path to tool_install.sh for mmaps actions

### LINKED ISSUE #756: mmaps on master
https://github.com/stm32-rs/stm32-rs/runs/7736728303?check_suite_focus=true

cc @adamgreig 

As mmaps on master branch work independently I can't test this CI

maybe just `make install` instead of `./scripts/tool_install.sh` fix it

### PR DESCRIPTION
**Pull request by newAM**
Closes #756 hopefully.

cc @burrbull

### CODE REVIEW

**Comment by newAM** [comment]
I think compare will still fail because it uses `pull_request_target:`, and is getting the `mmaps_pr.yml` file from the master branch.

**Comment by adamgreig** [comment]
We can't run the script from the PR, because it would add a security vulnerability - the PR may contain malicious code that compromises the GitHub token. That's why the action uses `pull_request_target` - we need to make sure we don't execute any code from the PR, only from the existing master branch. I think it should be OK to just use `master/` instead of `pr/` here?

**Comment by newAM** [comment]
Good catch!  Fixed.

**Review by adamgreig — APPROVED** [review]
thanks!

bors r+

**Pull request merged**
