### PR TITLE
normalize-docs

### PR DESCRIPTION
**Pull request by burrbull**
Unfortunately this feature still unstable (nightly rustfmt).
https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#normalize_doc_attributes

### CODE REVIEW

**Comment by adamgreig** [comment]
Seems like nightly rustfmt is also broken at the moment so I'm holding off on this. I wonder if we can update svd2rust to emit normal docstring comments instead.

**Comment by burrbull** [comment]
It was working with rust nightly 2019-07-22

**Comment by adamgreig** [comment]
Looks like it's been broken since 26th: https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html

**Comment by burrbull** [comment]
2019-07-31
All components except miri were restored.

**Comment by adamgreig** [comment]
please could you rebase?

**Comment by burrbull** [comment]
Sure.

**Comment by burrbull** [comment]
Done.

**Pull request merged**
