### PR TITLE
fix IWDG PR

### PR DESCRIPTION
**Pull request by usbalbin**
@burrbull 's

### CODE REVIEW

**Comment by usbalbin** [comment]
It take this error in f3xx-hal as proof that it worked very well :)
```
error[E0599]: no method named `unwrap_or` found for enum `PR` in the current scope
   --> src/watchdog.rs:136:14
    |
130 |           let psc = self
    |  ___________________-
131 | |             .iwdg
132 | |             .pr()
133 | |             .read()
134 | |             .pr()
135 | |             .variant()
136 | |             .unwrap_or(PR::DivideBy256);
    | |             -^^^^^^^^^ method not found in `PR`
    | |_____________|
    |
```

and the generated code for the `variant` method:

```rust
pub const fn variant(&self) -> PR {
    match self.bits {
        0 => PR::DivideBy4,
        1 => PR::DivideBy8,
        2 => PR::DivideBy16,
        3 => PR::DivideBy32,
        4 => PR::DivideBy64,
        5 => PR::DivideBy128,
        _ => PR::DivideBy256,
    }
}
```

Awesome, thanks!

**Review by burrbull — APPROVED** [review]

**Comment by burrbull** [comment]
@usbalbin  https://github.com/stm32-rs/stm32-rs/pull/992 makes xWDG registers 16-bits wide to access them with half-word read/write + some patch refactoring.
What do you think?
Could you reopen it by yourself?

**Comment by usbalbin** [comment]
> @usbalbin #992 makes xWDG registers 16-bits wide to access them with half-word read/write + some patch refactoring. What do you think? Could you reopen it by yourself?

I can not open a new one while #992 is open but if you close it, then sure

**Comment by burrbull** [comment]
@usbalbin Closed

**Pull request merged**
