### PR TITLE
Use PascalCase for values of enums

### PR DESCRIPTION
**Pull request by burrbull**
related feature in svd2rust
https://github.com/rust-embedded/svd2rust/pull/591

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
Nice, sounds good.

bors r+

**Comment by adamgreig** [comment]
Oops, still draft.

bors r-

**Comment by burrbull** [comment]
This is breaking change.
I wanted to discuss it at meeting, but forgot.

**Comment by adamgreig** [comment]
I think this is fine, the enums are much nicer in pascal case and I don't think many people match on them directly anyway; in any event it's a straightforward mechanical change.

bors r+

**Pull request merged**
