### PR TITLE
STM32C0 family support

### PR DESCRIPTION
**Pull request by dotcypress**
Initial support for STM32C0 family.

Mostly validated with [stm32c0xx-hal](https://github.com/stm32-rs/stm32c0xx-hal) and `Nucleo-C031C6`.

### CODE REVIEW

**Comment by dotcypress** [comment]
Ok, I think this PR is ready for review. 
Most of peripherals is validated, some of them still need attention.
Anyway it will be really helpful to have stm32c0 nightlies builds for stm32c0xx-hal development.

I'm not sure who gonna review that, but just in case pinging @adamgreig 🙃

**Comment by dotcypress** [comment]
Friendly reminder on this PR 🙂

cc @newAM @adamgreig

**Review by adamgreig — APPROVED** [review]
Thanks, and sorry for the wait! This looks good to me. Would you mind adding me as a crate owner for stm32c0 so I can publish it together with the rest when we do a release?

bors r+

**Comment by dotcypress** [comment]
Thank you @adamgreig 🎉

Crate ownership invite sent.

**Pull request merged**
