### PR TITLE
can F1

### PR DESCRIPTION
**Pull request by burrbull**

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]

**Comment by burrbull** [comment]
Not sure. Delete them instead?

**Comment by burrbull** [comment]
изображение

**Comment by adamgreig** [comment]
Right, CAN only exists on connectivity line (F105, F107), and F103, which means it's not ever present on F101/F102.

**Comment by burrbull** [comment]
> Right, CAN only exists on connectivity line (F105, F107), and F103, which means it's not ever present on F101/F102.

Done.

**Review by adamgreig — APPROVED** [review]

**Pull request merged**
